wallpaper {
	monitor = DP-2
	path = ~/Nextcloud2/pictures/wallpapers/bri-grass.jpeg
	fit_mode = cover
}

wallpaper {
	monitor = DP-3
	path = ~/Nextcloud2/pictures/wallpapers/bri-grass.jpeg
	fit_mode = cover
}
