theme = "mytheme"

[editor]
line-number = "relative"
mouse = false
bufferline = "multiple"
cursorline = true

[editor.lsp]
enable = true
auto-signature-help = true
display-messages = true

[editor.statusline]
left = ["mode", "spinner", "version-control", "file-name"]

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"
