theme = "ao"

[editor]
line-number = "relative"
mouse = false
rulers = [80]
bufferline = "multiple"
cursorline = true

[editor.lsp]
enable = true
auto-signature-help = true
display-messages = true

[editor.statusline]
left = ["mode", "spinner", "version-control", "file-name"]

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[keys.normal]
0 = "goto_line_start"
"$" = "goto_line_end"

[keys.normal.c]
r = ":sh cargo run 2>&1 || true"
c = ":sh cargo check 2>&1 || true"
b = ":sh cargo build 2>&1 || true"
t = ":sh cargo test 2>&1 || true"
